import 'package:firebase_core/firebase_core.dart';

import '../config/app_environment.dart';
import '../firebase_options_dev.dart' as dev;
import '../firebase_options_prod.dart' as prod;

/// Initializes Firebase with the options matching [env].
///
/// The `firebase_options_dev.dart` / `firebase_options_prod.dart` files are
/// generated by `flutterfire configure` (one per Firebase project).
Future<FirebaseApp> initializeFirebase(Environment env) {
  // On iOS/Android the native SDK may have already created the [DEFAULT] app
  // (from GoogleService-Info.plist / google-services.json), and it also
  // survives a hot restart — calling initializeApp again would throw
  // [core/duplicate-app].
  if (Firebase.apps.isNotEmpty) {
    return Future.value(Firebase.app());
  }
  final options = switch (env) {
    Environment.dev => dev.DefaultFirebaseOptions.currentPlatform,
    Environment.prod => prod.DefaultFirebaseOptions.currentPlatform,
  };
  return Firebase.initializeApp(options: options);
}
