import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:our_tribe/config/app_environment.dart';
import 'package:our_tribe/firebase_options_dev.dart' as dev;
import 'package:our_tribe/firebase_options_prod.dart' as prod;

/// Points the SDKs at the local emulator suite when the app is run with
/// `--dart-define=USE_FIREBASE_EMULATORS=true` (integration testing only).
const bool _useEmulators = bool.fromEnvironment('USE_FIREBASE_EMULATORS');

/// Initializes Firebase with the options matching [env].
///
/// The `firebase_options_dev.dart` / `firebase_options_prod.dart` files are
/// generated by `flutterfire configure` (one per Firebase project).
Future<FirebaseApp> initializeFirebase(Environment env) async {
  // On iOS/Android the native SDK may have already created the [DEFAULT] app
  // (from GoogleService-Info.plist / google-services.json), and it also
  // survives a hot restart — calling initializeApp again would throw
  // [core/duplicate-app].
  final FirebaseApp app;
  if (Firebase.apps.isNotEmpty) {
    app = Firebase.app();
  } else {
    final options = switch (env) {
      Environment.dev => dev.DefaultFirebaseOptions.currentPlatform,
      Environment.prod => prod.DefaultFirebaseOptions.currentPlatform,
    };
    app = await Firebase.initializeApp(options: options);
  }
  if (_useEmulators) {
    await FirebaseAuth.instance.useAuthEmulator('localhost', 9099);
    FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
  }
  return app;
}
