// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADwQlONinc82M7YZ0SD3zz9_ehP54o9hw',
    appId: '1:895248032225:web:d6d1a8e3f7b36f66c0f2a0',
    messagingSenderId: '895248032225',
    projectId: 'our-tribe-prod',
    authDomain: 'our-tribe-prod.firebaseapp.com',
    storageBucket: 'our-tribe-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaqwz7H8rmeKtitWKDrFIEGU9mM8FSunM',
    appId: '1:895248032225:android:7ec74c477ec2d913c0f2a0',
    messagingSenderId: '895248032225',
    projectId: 'our-tribe-prod',
    storageBucket: 'our-tribe-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMUIkXURJcjlCV0BtDj444IOTseRUg1YI',
    appId: '1:895248032225:ios:30ebe0b56d5c235fc0f2a0',
    messagingSenderId: '895248032225',
    projectId: 'our-tribe-prod',
    storageBucket: 'our-tribe-prod.firebasestorage.app',
    iosBundleId: 'com.ourtribe.app',
  );
}
