// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChTc8O0we7xZWB68QRQvrmbuhigTpAA_w',
    appId: '1:1055735712195:web:29876a5846dcef81641576',
    messagingSenderId: '1055735712195',
    projectId: 'our-tribe-dev',
    authDomain: 'our-tribe-dev.firebaseapp.com',
    storageBucket: 'our-tribe-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF6axsrjgVxteoPUx3Q724vTaut6u3-Hg',
    appId: '1:1055735712195:android:0220eb8ebbaafb9c641576',
    messagingSenderId: '1055735712195',
    projectId: 'our-tribe-dev',
    storageBucket: 'our-tribe-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLuBxqHw-ar9JwtAwb7Qvum8Iv7CT3oZM',
    appId: '1:1055735712195:ios:9dc1a3781d1b7215641576',
    messagingSenderId: '1055735712195',
    projectId: 'our-tribe-dev',
    storageBucket: 'our-tribe-dev.firebasestorage.app',
    iosBundleId: 'com.ourtribe.app.dev',
  );
}
